export const REMINDER_TYPES=Object.freeze(['activity','flight','checkin','checkout','reservation','task_due','task_overdue','settlement','budget','document','trip_start','daily_summary','manual']);
export const DEFAULT_NOTIFICATION_PREFERENCES=Object.freeze({activities:true,flights:true,reservations:true,tasks:true,budget:true,sharedExpenses:true,documents:true,dailySummary:false,push:false,leadMinutes:120,quietStart:'22:00',quietEnd:'07:00',timeZone:'America/Costa_Rica',mutedTripIds:[]});
export function validTimeZone(value){try{new Intl.DateTimeFormat('en',{timeZone:value}).format();return true;}catch{return false;}}
export function zonedLocalToUtc(localIso,timeZone){if(!/^\d{4}-\d\d-\d\dT\d\d:\d\d/.test(localIso)||!validTimeZone(timeZone))throw new Error('Fecha o zona horaria inválida.');const wanted=Date.UTC(...localIso.slice(0,16).split(/[-T:]/).map(Number).map((v,i)=>i===1?v-1:v));let guess=wanted;for(let i=0;i<3;i++){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(guess)).filter(p=>p.type!=='literal').map(p=>[p.type,Number(p.value)]));const represented=Date.UTC(parts.year,parts.month-1,parts.day,parts.hour,parts.minute);guess+=wanted-represented;}return new Date(guess).toISOString();}
export function isQuietTime(instant,timeZone,start='22:00',end='07:00'){const hourMinute=new Intl.DateTimeFormat('en-GB',{timeZone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(instant));return start<=end?hourMinute>=start&&hourMinute<end:hourMinute>=start||hourMinute<end;}
export function preferenceAllows(type,prefs=DEFAULT_NOTIFICATION_PREFERENCES,tripId=''){if((prefs.mutedTripIds||[]).includes(tripId))return false;const map={activity:'activities',flight:'flights',checkin:'reservations',checkout:'reservations',reservation:'reservations',task_due:'tasks',task_overdue:'tasks',settlement:'sharedExpenses',budget:'budget',document:'documents',daily_summary:'dailySummary'};return map[type]?prefs[map[type]]!==false:true;}
export function reminderKey({userId,tripId,type,resourceId='general',scheduledAt}){return [userId,tripId,type,resourceId,String(scheduledAt).slice(0,16)].join('_').replace(/[^a-zA-Z0-9_-]/g,'-').slice(0,500);}
export function crossedBudgetThreshold(previous,current){return [80,90,100].filter(level=>previous<level&&current>=level);}
export function safeNotificationTarget(path=''){return /^\/(dashboard|dashboard\.html)(\?|#|$)/.test(path)?path:'/dashboard';}
