import { auth, db } from '../../core/firebase-config.js';
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, onSnapshot, orderBy, query, serverTimestamp, updateDoc, writeBatch } from 'firebase/firestore';
import { packingProgress } from '../dashboard/dashboard-summary.js';

export const PACKING_CATEGORIES=['Ropa','Higiene','Tecnología','Documentos','Medicamentos','Accesorios','Otros'];
const safe=(value='')=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));

export const PackingList={
  items:[],unsubscribe:null,editingId:null,filters:{category:'',assignee:'',status:''},
  get tripId(){return window.TripsManager?.currentTrip?.id||localStorage.getItem('currentTripId');},
  async init(){if(auth.currentUser&&this.tripId)await this.initSync();},
  async initSync(){this.cleanup();if(!auth.currentUser||!this.tripId)return;await this.migrateLegacy();this.unsubscribe=onSnapshot(query(collection(db,`trips/${this.tripId}/packingItems`),orderBy('createdAt','desc')),snapshot=>{this.items=snapshot.docs.map(d=>({id:d.id,...d.data()}));this.render();window.TripsManager?.loadDashboardProgressiveContent?.();},error=>{const host=document.getElementById('packingListContainer');if(host)host.innerHTML=`<p class="budget-state budget-state--error">${safe(error.message)}</p>`;});},
  async migrateLegacy(){const target=collection(db,`trips/${this.tripId}/packingItems`);if(!(await getDocs(target)).empty)return;const legacy=await getDoc(doc(db,`trips/${this.tripId}/data/packing`));const raw=legacy.exists()?legacy.data()?.items:[];const items=Array.isArray(raw)?raw:Object.values(raw||{}).flat();if(!items.length)return;const batch=writeBatch(db);items.forEach(item=>{const ref=doc(target);batch.set(ref,{name:String(item.name||'Artículo'),category:PACKING_CATEGORIES.includes(item.category)?item.category:'Otros',quantity:Math.max(1,Number(item.quantity)||1),packed:Boolean(item.checked),assignee:item.owner||null,notes:item.notes||'',createdBy:auth.currentUser.uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),migratedFrom:'data/packing'});});await batch.commit();},
  open(options={}){if(!this.tripId||!auth.currentUser)return;document.getElementById('packingListModal')?.remove();this.editingId=options.create?'new':null;const modal=document.createElement('div');modal.id='packingListModal';modal.className='budget-gallery-modal';modal.innerHTML=`<section class="budget-gallery checklist-panel" role="dialog" aria-modal="true" aria-labelledby="packingTitle"><header><div><p class="budget-kicker">旅の荷物 · EQUIPAJE</p><h2 id="packingTitle">Lista de equipaje</h2></div><button data-close aria-label="Cerrar">×</button></header><div id="packingFormHost"></div><div class="checklist-toolbar"><button data-new>＋ Agregar artículo</button><label>Categoría<select data-filter="category"><option value="">Todas</option>${PACKING_CATEGORIES.map(c=>`<option>${c}</option>`).join('')}</select></label><label>Estado<select data-filter="status"><option value="">Todos</option><option value="pending">Pendientes</option><option value="packed">Empacados</option></select></label><label>Responsable<input data-filter="assignee" placeholder="Nombre o correo"></label></div><div id="packingSummary" class="checklist-summary"></div><div id="packingListContainer"><p class="budget-state">Cargando equipaje…</p></div></section>`;document.body.append(modal);modal.querySelector('[data-close]').onclick=()=>this.closeModal();modal.querySelector('[data-new]').onclick=()=>{this.editingId='new';this.renderForm();};modal.querySelectorAll('[data-filter]').forEach(field=>{field.value=this.filters[field.dataset.filter];field.oninput=()=>{this.filters[field.dataset.filter]=field.value;this.render();};});this.renderForm();this.initSync();},
  renderForm(){const host=document.getElementById('packingFormHost');if(!host)return;if(!this.editingId){host.innerHTML='';return;}const item=this.editingId==='new'?{}:this.items.find(i=>i.id===this.editingId)||{};host.innerHTML=`<form class="expense-form"><h3>${item.id?'Editar':'Nuevo'} artículo</h3><div class="expense-form__grid"><label>Nombre*<input name="name" required maxlength="120" value="${safe(item.name)}"></label><label>Categoría<select name="category">${PACKING_CATEGORIES.map(c=>`<option ${item.category===c?'selected':''}>${c}</option>`).join('')}</select></label><label>Cantidad<input name="quantity" type="number" min="1" max="99" value="${item.quantity||1}"></label><label>Responsable<input name="assignee" value="${safe(item.assignee)}"></label><label class="expense-form__wide">Notas<textarea name="notes" maxlength="400">${safe(item.notes)}</textarea></label></div><div class="expense-form__buttons"><button type="button" data-cancel>Cancelar</button><button type="submit">Guardar artículo</button></div></form>`;host.querySelector('[data-cancel]').onclick=()=>{this.editingId=null;this.renderForm();};host.querySelector('form').onsubmit=event=>this.save(event,item);},
  render(){const host=document.getElementById('packingListContainer');if(!host)return;const progress=packingProgress(this.items);document.getElementById('packingSummary').innerHTML=`<strong>${progress.percent}% empacado</strong><span>${progress.packed} empacados · ${progress.pending} pendientes</span>`;const visible=this.items.filter(i=>(!this.filters.category||i.category===this.filters.category)&&(!this.filters.assignee||String(i.assignee||'').toLowerCase().includes(this.filters.assignee.toLowerCase()))&&(!this.filters.status||(this.filters.status==='packed')===Boolean(i.packed)));const groups=visible.reduce((acc,item)=>{(acc[item.category]||=[]).push(item);return acc;},{});host.innerHTML=Object.keys(groups).length?Object.entries(groups).map(([category,items])=>{const all=items.every(i=>i.packed);return `<section class="packing-group"><header><h3>${safe(category)}</h3><button data-category="${safe(category)}" data-pack="${!all}">${all?'Desmarcar categoría':'Empacar categoría'}</button></header>${items.map(item=>`<article class="checklist-row ${item.packed?'is-complete':''}"><label><input type="checkbox" data-toggle="${item.id}" ${item.packed?'checked':''}><span><strong>${safe(item.name)}${item.quantity>1?` ×${item.quantity}`:''}</strong><small>${item.assignee?safe(item.assignee):'Sin responsable'}${item.notes?' · '+safe(item.notes):''}</small></span></label><div><button data-edit="${item.id}">Editar</button><button data-delete="${item.id}">Eliminar</button></div></article>`).join('')}</section>`;}).join(''):'<p class="budget-state">No hay artículos en esta vista.</p>';host.querySelectorAll('[data-toggle]').forEach(e=>e.onchange=()=>updateDoc(doc(db,`trips/${this.tripId}/packingItems/${e.dataset.toggle}`),{packed:e.checked,updatedAt:serverTimestamp()}));host.querySelectorAll('[data-edit]').forEach(e=>e.onclick=()=>{this.editingId=e.dataset.edit;this.renderForm();});host.querySelectorAll('[data-delete]').forEach(e=>e.onclick=()=>this.remove(e.dataset.delete));host.querySelectorAll('[data-category]').forEach(e=>e.onclick=()=>this.toggleCategory(e.dataset.category,e.dataset.pack==='true'));},
  async save(event,existing){event.preventDefault();const data=new FormData(event.currentTarget),name=String(data.get('name')||'').trim();if(!name)return;const duplicate=this.items.find(item=>item.id!==existing.id&&item.name.trim().toLowerCase()===name.toLowerCase());if(duplicate&&!confirm(`Ya existe “${duplicate.name}”. ¿Agregarlo de todas formas?`))return;const payload={name,category:String(data.get('category')),quantity:Math.max(1,Math.min(99,Number(data.get('quantity'))||1)),assignee:String(data.get('assignee')||'').trim()||null,notes:String(data.get('notes')||'').trim(),updatedAt:serverTimestamp()};if(existing.id)await updateDoc(doc(db,`trips/${this.tripId}/packingItems/${existing.id}`),payload);else await addDoc(collection(db,`trips/${this.tripId}/packingItems`),{...payload,packed:false,createdBy:auth.currentUser.uid,createdAt:serverTimestamp()});this.editingId=null;this.renderForm();window.Notifications?.success?.('Artículo guardado.');},
  async toggleCategory(category,packed){const batch=writeBatch(db);this.items.filter(item=>item.category===category).forEach(item=>batch.update(doc(db,`trips/${this.tripId}/packingItems/${item.id}`),{packed,updatedAt:serverTimestamp()}));await batch.commit();},
  async remove(id){const item=this.items.find(i=>i.id===id);if(!item||!confirm(`¿Eliminar “${item.name}”?`))return;await deleteDoc(doc(db,`trips/${this.tripId}/packingItems/${id}`));},
  reinitialize(){if(auth.currentUser)this.initSync();},cleanup(){this.unsubscribe?.();this.unsubscribe=null;},closeModal(){document.getElementById('packingListModal')?.remove();},
  renderList(){this.render();},setFilter(key,value){this.filters[key]=value;this.render();},addCustomItem(){this.open({create:true});}
};
window.PackingList=PackingList;
